### ISSUE TITLE
Multiple languages or setting for the language (for example Audible.de instead of Audible.com)

### ISSUE THREAD

**Issue by DFelten** [macr0dev/Audiobooks.bundle#2]
Thanks for this great audiobook agent! 

One suggestion: A setting for the language would be great. My Audiobooks are mostly in German and so I need to find the data on Audible.de and not on Audible.com. If I change audible.com to audible.de in __init__.py  it's working. A setting for this would be great.

It would be even better if several languages were checked.

**Comment by dethrophes** [comment]
I added support for this on my fork.
https://github.com/dethrophes/Audiobooks.bundle/commit/5cd715387cdf7a9b163e93757752d26cbfacd320

**Comment by macr0dev** [comment]
I like the way that you've added in the support for other sites and languages into your fork.  But I wonder if it doesn't make an assumption that not everyone would make.  Which is that your default plex language determines which audible site you want to hit.  I've noticed in the audible subreddit that people have mentioned differences in availability between different geographic locations.  I'm going to integrate your code into mine, but I'm likely going to make it an option to choose from rather than an automatic selection.

This way, if people wanted to switch between sites and manually search for books they can do so.

**Comment by dethrophes** [comment]
It's not based on the default language. 
It's based on the library laguage. When you create a collection/lib you select the language it is in. 

So I have 3 libs for audiobooks one in french, german , and english. 

This is how all the agents do it and it makes sense that way.

**Comment by dethrophes** [comment]
Here is what it looks like. 
![grafik](https://user-images.githubusercontent.com/1491187/28395921-23f70cd0-6cf8-11e7-855d-cb2329b4b93d.png)

**Comment by dethrophes** [comment]
Oh and then there is the option in the lib to select which site to use for english. 
i.e. audible.com, audible.co.uk, or auduble.com.au.

**Comment by macr0dev** [comment]
Interesting.  I'd honestly never paid attention to that language setting.  Thanks for pointing that out.

How much do you know about title availability on audible.com specifically?  I know that there are non-English versions of many books on there.  Being only English speaking myself, I can't decide if there is an advantage to creating multiple libraries for different languages, unless there is an availability issue affecting the scraping.

Do you have much experience with that?

**Comment by dethrophes** [comment]
Well it's complicated....

First point is, the main reason i have libs in different languages is that it's useful. 
Somtimes I want to watch stuff in a specific language. 
Or my siblings have access to my server and only speak some languages so, then I just ive them access to the libs in the languages they know.  etc...

As for audible, 
Just like netflix etc... the different location sites have different distribution rights. 
So it happens that you will only find an english book on a specific english audible site. 

CErtainly the main selction of books in a language are on that countries sites. 
This is why I have audible accouts in the us, france and germany.

Having siad that audible is unique in that audible.com does allow internaltional users to use it. 
and infact audible.es redirects to audible.com. i.e. all the spanish books are on audbile.com..

Furhtermore as audible are getting more "origionals" marked as exclusive. This are created by audible from teh outset to be on all audible sites worldwide. 
This is why you now see more french, german etc... books on audible.com  and vice versa, this is however only for a small subset of the books. 


As such yes it makes sense to have the support for the different sites.
What could be argued as better is if he agent would just query all the audible sites. ...

**Comment by macr0dev** [comment]
> What could be argued as better is if he agent would just query all the audible sites. ...

now THAT is an interesting idea.  It gives me the idea of letting people pick which sites they want to poll, and only check those.  For example, someone who speaks german and english may want to check .com, .co.uk, and .de.  Where as someone who speaks Spanish may want a different set.  So rather than checking _them all_, just check the ones that are marked.

Also, the 'fix match' has language options that could be used to prioritize which site is checked....   this is good stuff.  I think I see have a few ideas to flesh out this weekend.  

I appreciate the discussion.  I don't have any multi-language listeners in my immediate circle.

**Comment by dethrophes** [comment]
well Spanish is a good example. with audible there is no easy way to distinguish between spanish and english as they are both on audible.com.

Actually, I approachig a point where I have to say that audible just isn't the best option... It doesn'T have th info for a lot of books, even books I bought on audible. 
The books only turn up in the search results if audible can currently sell them. 

As such scrapping amazon, goodreads, librevox or something might be a much better option. 
Or possibly even reusing some of the calibre scraping plugins. 

Also as I say i actually want the ability to have different libs for different languages. it's the reason I'd actually like to see collection grouping in audible, as I have 7 different tv show collections for example.
As such if you do change it to allow a matrix of sites that will be tried, it will get messy as the normal options are global. As such the only way you could do it so as to work for different languages would be to let it be configured for each language..... 

On top of that, I'm still questioning just how useful the audiobook support in plex is.... as it only remembers your location in the current file, not in the album. It also doen'T display any indicator as to how much of the album you have listened to.

**Comment by macr0dev** [comment]
> well Spanish is a good example. with audible there is no easy way to distinguish between spanish and english as they are both on audible.com.

That's actually not entirely true.  If you visit the advanced search page on audible, there is a selection to pick languages.  Which adds a tag which includes a language code.  So that could be something helpful.  Especially from the 'fix this match' option where you can pick the language.  
  
I get what you're about Audible's results only including currently available titles.  And as much as that sucks, the search options on Audible and GoodReads appear to suck more.  I couldn't really find an advanced search on good reads, which brings back WAY too many results in all formats.  Amazon HAS advanced search, but it has at least 3 different audiobook choices.  And the generic one didn't include an audible exclusive.  It said it found it in 'other departments.'  As for librevox, most of my books aren't even there.  For whatever that's worth.

On the languages front, if I build it where you get to pick which sites to include and pick a default library language - you can still do separate libraries.  But this way you have the option to do them all together if you are only doing like two languages.  It's possible I could always add in an option to pick up another MP3 tag.  Something that might designate language.  but then people would need to retag their files.

As for audiobook support in plex, I honestly don't use it.  I'm just a cataloging nerd and thought I'd share my agent.  It also give me a way to share my library and let my friends see what I've got.  I listen either via the audible app or an audiobook app on my phone.  Part of me hopes they'll see the desire from the community and make support for it a little better.  I read recently that they added support for the iTunes audiobook format.  So I have hope.

For the moment I'm going to write down a few things and come up with a plan of attack.  Maybe I can have some more options knocked out by the end of the weekend.  There are some more plex based things that I don't have working that I'd like to see.  Album cover in the manual match selection, etc.

Your contributions and our conversation have sparked me into wanting to work on this thing again.

**Comment by dethrophes** [comment]
Well it depends on how you go about searching the sites. 
What I have done in the past is use google to search the sites. 
e,g,
https://www.google.de/search?q=Arthur+C.+Clarke+site%3Agoodreads.com&btnK=Google+Search
https://www.google.de/search?q=Arthur+C.+Clarke+site%3Aamazon.com&btnK=Google+Search

Then filter the results based on the url structure. 
e.g. goodreads author has a url like "www.goodreads.com/author/show/7779.Arthur_C_Clarke"


There are a couple of things which I also haven't figured out "yet".
1. correct the Author/Artist in the Album Agent. It doesn't seem to be possible.
2. Access the files in the Agent. 


What I'm begininng to think may be the better route is to just load the info from the file tags... I have jpgs, description, author, etc... already in the metainfo... so it would seem easier to just use that. 

That way it would work better between booksonic, plex, bliss etc...

**Comment by macr0dev** [comment]
I've modified your automatic site selection and added an option to turn it off and select the site manually in the preferences.  I've decided this is kind of the best of both worlds.  

If someone wants to keep all their books in the same library, they can leave the manual option unchecked and then do manual searches to specific sites by selecting the language at search time.  Otherwise, it's defaulted to audible.com.  This way anyone who was already using the plugin will not to change their options to continue on the way things were.

I'm going to add doing some author stuff to my todo list.  We should also find a better way to chat.
