### ISSUE TITLE
Album sorting goes from newest to oldest, instead of from oldest to newest

### ISSUE THREAD

**Issue by rnyberg** [macr0dev/Audiobooks.bundle#3]
This might be a Plex problem though, but the only way to have albums go from first book to last book is to set the "Originally available" field manually to be wrong.

**Comment by dethrophes** [comment]
How do you mean?

**Comment by rnyberg** [comment]
I'll add screenshots later

**Comment by macr0dev** [comment]
This is really more of a Plex sorting issue.  Not really a way to control this.  Since the books don't come with preceding numbers for sorting, there's not anything to be done.

**Comment by dethrophes** [comment]
You can do this by changing the album order in the library settings. 
By default it's newest first, you can change it to oldest first. 

![image](https://user-images.githubusercontent.com/1491187/28546902-a15baf82-70cc-11e7-866a-28b143d76b31.png)

**Comment by macr0dev** [comment]
Well, yes and no.  It actually sorts using the year rather than the entire 'originally available' date.  Which means that if two books come out in the same year, It will sort between those two alphabetically by title.

For example, Going Home and Escaping Home were both released in 2013.  One on 10/28 and one on 10/30, respectively.  However despite the library being set to oldest first, Escaping home is listed first because E before G.
