### ISSUE TITLE
Is tagging required?

### ISSUE THREAD

**Issue by steco** [macr0dev/Audiobooks.bundle#38]
This might be obvious, so sorry for the basic question.  I am trying to work out whether I can avoid having to tag my audiobook files and have the agent work instead from the folder names (this is how the agent for TV shows works).

I've tried changing the agent to use `media.items[0].parts[0].file` to pull out the filename, but it seems that media.items is always empty.  Is this because this is derived from Agent.Album instead of Agent.Movies or is there something else different ?

Thanks!

**Comment by macr0dev** [comment]
Yeah, so the interesting thing about how it handles music is that the directory structure really plays ZERO part in the sorting of files.

By design, the music library groups tracks by album name underneath each artist name, and it does this by tag.  Your files could be all in one folder and the tags will determine how they're grouped. 

This plug in just plays off of that design by looking up the album/artist as title/author on Audible.  There's not really a way that I know of to do things by folder structure.

**Comment by steco** [comment]
Ah great - thanks for the explanation!
