### ISSUE TITLE
Some HTML tags are not being stripped (<em> and <strong>) from review/synopsis

### ISSUE THREAD

**Issue by brandonscript** [macr0dev/Audiobooks.bundle#42]
<img width="1100" alt="Screen Shot 2019-07-31 at 3 12 52 PM" src="https://user-images.githubusercontent.com/1480253/62251848-eab1b000-b3a5-11e9-85c7-0505be5dd2c6.png">

Source match: https://www.audible.com/pd/One-Dark-Throne-Audiobook/B073ZJL559?qid=1564611314&sr=1-1&pf_rd_p=e81b7c27-6880-467a-b5a7-13cef5d729fe&pf_rd_r=ZFN93TVMQQ7572KHY915&ref=a_search_c3_lProduct_1_1

Appears to do it for the following tags (so far as I've seen):

```
<em>
<strong>
<ul>
<ol>
<li>
```

**Comment by macr0dev** [comment]
Thanks for finding more of these.  The major rewrite of the site from a year or two ago introduced some interesting challenges.

**Comment by brandonscript** [comment]
I bet! Glad to help, and thanks to the release of “Prologue” for iOS, this plugin has saved my 🥓

**Comment by macr0dev** [comment]
I'm not an Apple guy, what's Prologue?

**Comment by brandonscript** [comment]
https://www.reddit.com/r/PrologueApp/comments/cff91k/prologue_is_now_available_on_the_app_store/

**Comment by macr0dev** [comment]
Holy crap.  That's awesome!  With a decent player around, Audiobooks on Plex might become a bigger deal.  Guess I need to stay on top of this plugin more!  lol

If they make one for Android I might actually listen to my books through it.  Right now I just do this because I'm a data hoarder and like having my books organized.  I use different apps to listen.
